package org.apache.texera.docs.scripts.operators

import org.apache.texera.docs.scripts.OperatorScript

// Placeholder. Real content is regenerated by OperatorScriptGenerator:
//   sbt 'Docs/runMain org.apache.texera.docs.scripts.OperatorScriptGenerator'
object OperatorScriptRegistry {
  val all: Seq[OperatorScript] = Seq.empty
}
